### ISSUE TITLE
Endpoints unable to process high traffic Caliper messages should return 429 or 503 status codes

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-central#165]
During a local discussion about Caliper message stream management (e.g., throttling, message filtering, etc.) it was suggested by a colleague that endpoints unable to process high traffic requests should return appropriate HTTP status codes to a sender such as 429 or 503:

> For practical implementations senders should be able to cache and stop sending if they get the following status codes when they put data.  Receivers should be prepared to send these codes when appropriate to prevent data loss.

> 429 Too Many Requests (RFC 6585)
> 503 Service Unavailable

**Comment by ViktorHaag** [comment]
https://github.com/IMSGlobal/caliper-central/issues/45

**Comment by ViktorHaag** [comment]
This might be best merged into https://github.com/IMSGlobal/caliper-central/issues/45

**Comment by ViktorHaag** [comment]
I think it makes sense not to add wording in our spec around this, but lean on HTTP semantics for this. I.e. as you point out [429](https://tools.ietf.org/html/rfc6585#page-3) for too many requests if handling flooding at the app layer for flow control, or potentially [503](https://tools.ietf.org/html/rfc7231#page-63) if server-fall-down and be unavailable for caller (because flooded).
