### ISSUE TITLE
Caliper Profile for consideration: Cumulative Progress

### ISSUE THREAD

**Issue by benadida** [IMSGlobal/caliper-central#190]
submitted by Clever, working with partners to formulate a progress profile for Caliper, where learning applications can submit cumulative progress events. We would love your comments. We care strongly about the use case, and are very flexible on the technical implementation (especially as we're new to Caliper.)

https://docs.google.com/document/d/1714ePpQX_Id4KBX16SILw_xspgHpBQoJzkEQjz9Dcgw/edit

**Comment by ViktorHaag** [comment]
One aspect of Caliper I feel we should hew closely to is the concept that Caliper makes statements of fact about a user's activity, first and foremost. I can see that a Caliper event, therefore might be "Student Watches Video [with added context]", but am less convinced that we should think about events that say "Student is 40% of the way through Video".

I'd propose instead of having a full-on profile for Progress that instead we focus on:
- How can we represent progress _as a thing_ in a way that's simple and admits for what we might think of typical ways of handling progress-through-something (time-duration, percentage-complete, milestone-x-of-y seem the obvious ones to me)? We're probably going to need to do this anyway, whether we admit for some kind of "Progress Event" or whether we decorate other events...
- We consider allowing for our existing events to accept this progress thing as a contextual decoration, rather than having statements about general progress be the vehicle -- this would imply that a user's "progress" is a contextual property of some other, more concrete activity.

For use cases of lower fidelity where the sensor making the statement is getting low-res information from another component that only communicates "progress information" (of some sort) to the sensor, I suspect that the sensor in this case should either (a) use Tool Use to communicate "general user activity" about which it really knows little else, or (b) if it does know more about the likely user activity underpinning the user's activity it could make careful use of the more specific Caliper events -- for example, if the sensor "knows" that a user is "watching a video" but gets only "percentage complete" telemetry from the video player, it could create "MediaEvent.action==Viewed" events with an attached progress thing to communicate this activity.

**Comment by benadida** [comment]
@ViktorHaag I'm super amenable to that.

For the sake of making incremental progress, assuming that we go with the data model more aligned with what you describe above, are you supportive of the use case of cumulative progress expressed via Caliper?

**Comment by ViktorHaag** [comment]
I think I'm supportive of individual events being able to report an aspect of progress as a factual part of the context around the learning event. I'm more supportive of an individual event being able to say
- as part of this View Event's context, I can tell you that they have reached milestone 5 of 10
- as part of this View Event's context, I can tell you that they have reached time 5:43 of 10:15

I'm less supportive of asserting that the user is, with any particular event, "80% done". I can see some cases where making such statements might make sense, and other cases where this decision is clearly an inference based on examining a group of facts, and I get uncomfortable when we put those aggregating statements into the activity stream and treat them as if they were facts...

**Comment by padraig-ohiceadha** [comment]
I think that it would be very useful to be able to link it to Caliper's support of Learning Objectives and CASE Competencies.
E.g. to be able to say
Person A achievedMastery of LearningObjective CCSS.MATH.CONTENT.6.NS.B.4 generating Evidence object
or Person A demonstrated the Competency <CASE identifier> generating Evidence object.

Potentially the model for Evidence could be influenced the the IMS Comprehensive Learner Record ( [https://www.imsglobal.org/activity/comprehensive-learner-record](url).

**Comment by arwhyte** [comment]
Closing in favor of #202.
